Feature/cakephp challenge1
miki123k/quelcode-cakephp pull request #2
Opened 2020-09-03 06:18 UTC by miki123k

# 実装内容
- 商品詳細欄
- 出品画像の登録機能
- カウントダウンタイマー

## 参考にしたサイト
http://www.hp-stylelink.com/news/2014/07/20140715.php
https://qiita.com/kurosu93/items/239e14df7ea20091a53b

2020-09-04 02:50 UTC, Yuzunoha commented
レビューしたら✓
- [x] 画像フォルダのgitignore/gitkeep
- [ ] タイマ
- [ ] 画像アップロード
- [ ] コーディング

2020-09-04 02:55 UTC, Yuzunoha commented
詳細設計では
>jpg,JPG,jpeg,JPEG,png,PNG,gif,GIFが拡張子の場合のみアップロードを許可。

とありますが `test.JPG` というファイルを指定すると `jpg,png,gif形式のみアップロード可能です` のメッセージが出ます。

修正と動作確認をお願いします！

2020-09-04 03:06 UTC, Yuzunoha requested changes

2020-09-04 03:06 UTC, Yuzunoha commented on html/mycakeapp/src/Template/Auction/view.ctp
> +					var nowDate = new Date();
現在時刻はJavaScript由来でなくPHP由来のものを使ってください。

現在時刻をJavaScriptで取得するとクライアント毎に時間が異なるため、ある人はオークションがタイムアップ表示で、ある人は継続中表示という事が起こります。

つまり最初にサーバ取得した現在時刻をJSに渡して、JSで1秒ずつカウントダウンするようにしてください。

2020-09-04 03:09 UTC, Yuzunoha commented on html/mycakeapp/src/Template/Auction/view.ctp
> +					var nowDate = new Date();
詳細設計書のこの修正で、現在時刻の取得方法をPHPからJavaScriptに変えていたのですね。見落としていました。
今回詳細設計書の修正は不要ですので、前述の通り現在時刻をPHPから取得するようにしてください。

![image](https://user-images.githubusercontent.com/22877094/92195211-5a4a7680-eea7-11ea-97b7-2df6e527aaa5.png)

2020-09-04 06:25 UTC, miki123k commented on html/mycakeapp/src/Template/Auction/view.ctp
> +					var nowDate = new Date();
ご指摘を受けて自分でも調べてみました。JavaScript内で時間を取得してしまうとローカルデバイスの時刻を取得してしまうとのことで確かにユーザーによって終了時刻までの残り時間がずれる可能性がありました。
その知識がなかったためJavaScript内で時刻を取得してしまっていましたのでPHP由来のものを使うよう変更いたしました。
今後気をつけたいと思います。ありがとうございます。

2020-09-07 00:40 UTC, Yuzunoha approved these changes
OKです！！承認しました！！！

2020-09-07 05:17 UTC, merged